/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package client.gui;

import cards.Card;
import helpers.Debug;
import java.awt.event.MouseEvent;
import java.awt.event.MouseListener;
import java.util.ArrayList;
import java.util.function.Consumer;

/**
 *
 * @author pseudo
 */
public class CardOrderPopup extends javax.swing.JDialog {
    ArrayList<Card> unordered, ordered;
    
    /**
     * Creates new form CardDisplay
     */
    public CardOrderPopup(ArrayList<Card> cards, Consumer<ArrayList<Card>> func) {
        super(new javax.swing.JFrame(), true);
        initComponents();
        unordered = cards;
        ordered = new ArrayList<>();
        unordered.forEach((card) -> {
            card.updatePanel();
            add(card.panel);
            card.panel.addMouseListener(orderAdapter(card, func));
        });
        java.awt.EventQueue.invokeLater(() -> {
            addWindowListener(new java.awt.event.WindowAdapter() {
                @Override
                public void windowClosing(java.awt.event.WindowEvent e) {
                    unordered.forEach((card) -> {
                        ordered.add(card);
                    });
                    func.accept(ordered);
                    dispose();
                }
            });
            pack();
            setVisible(true);
        });
    }

    java.awt.event.MouseAdapter orderAdapter(Card card, Consumer<ArrayList<Card>> func) {
        return new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                if (evt.getButton() == MouseEvent.BUTTON1) {
                    Debug.println("Selected an ordering card");
                    unordered.remove(card);
                    card.panel.removeAll();
                    ordered.add(card);
                    if (unordered.isEmpty()){
                        func.accept(ordered);
                        dispose();
                    } else {
                        remove(card.panel);
                        pack();
                    }
                }
            }
        };
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(100, 100));
        getContentPane().setLayout(new java.awt.FlowLayout());

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
